### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by abhijit79** [patroni/patroni#3101]
### What happened?

After system reboot replica can't catchup with the leader.
Could see following error in patroni logs.

`2024-07-11 15:38:53,527 INFO: master_timeline=6
2024-07-11 15:38:53,537 ERROR: Exception when working with master via replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 197, in _check_timeline_and_lsn
    history = bytes(cur.fetchone()[1]).decode('utf-8')
TypeError: string argument without an encoding`

### How can we reproduce it (as minimally and precisely as possible)?

We have seen this issue with:
patroni version: `2.0.2`
PostgreSQL version: `15.6`

### What did you expect to happen?

It seems the issue is in the statement: `history = bytes(cur.fetchone()[1], encoding='utf8').decode('utf-8')`

When we tried this code, it is giving the error same as the error in patroni log file.
```
with psycopg2.connect(dbname = dbname, user= user, password=password, replication=replication) as conn:
    conn.autocommit = True
    with conn.cursor() as cur:
        cur.execute('IDENTIFY_SYSTEM')
        master_timeline = cur.fetchone()[1]
        print('master_timeline=', master_timeline)
        cur.execute('TIMELINE_HISTORY %s', (master_timeline,))
        history = bytes(cur.fetchone()[1]).decode('utf-8')
        print('master: history=%s', history)
```

Error:
```
master_timeline= 6
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    history = bytes(cur.fetchone()[1]).decode('utf-8')
TypeError: string argument without an encoding`
```

But when we changed the statement `history = bytes(cur.fetchone()[1]).decode('utf-8')` to `history = bytes(cur.fetchone()[1], encoding='utf8').decode('utf-8')`, it worked fine.
```
master_timeline= 6
master: history=%s 1	0/80000A0	no recovery target specified

2	0/90000A0	no recovery target specified

3	0/A0000A0	no recovery target specified

4	0/100000A0	no recovery target specified

5	0/130000A0	no recovery target specified
```

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.0.2
-   PostgreSQL version: 15.6

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> patroni version: 2.0.2

Upgrade ASAP
