### ISSUE TITLE
Missing cdiff in requirements

### ISSUE THREAD

**Issue by korbajan** [patroni/patroni#3104]
### What happened?

requried ydiff has to be at least on 1.2.0 version (https://github.com/patroni/patroni/blob/master/requirements.txt#L13) so having ydiff 1.3.0 available this one will be installed. 
Unfortunately ydiff 1.3.0 does not provide PatchStream which leads to importing it from cdiff:
https://github.com/patroni/patroni/blob/master/patroni/ctl.py#L44-L51
but cdiff is not installed (as it is not required based on https://github.com/patroni/patroni/blob/master/requirements.txt)

### How can we reproduce it (as minimally and precisely as possible)?

Install patroni and run patronictl. 
You will get:
```
2024-07-16 11:38:46,367 - [MAIN] - ERROR - ProcessExecutionError: Failed running command: ['/opt/patroni/bin/patronictl', '-c', '/etc/patroni.conf', 'dsn'] (Traceback (most recent call last):
File "/opt/patroni/lib/python3.11/site-packages/patroni/ctl.py", line 31, in <module>
from ydiff import markup_to_pager, PatchStream
ImportError: cannot import name 'PatchStream' from 'ydiff' (/opt/patroni/lib/python3.11/site-packages/ydiff.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/patroni/bin/patronictl", line 5, in <module>
from patroni.ctl import ctl
File "/opt/patroni/lib/python3.11/site-packages/patroni/ctl.py", line 33, in <module>
from cdiff import markup_to_pager, PatchStream
ModuleNotFoundError: No module named 'cdiff'
).
ProcessExecutionError: Failed running command: ['/opt/patroni/bin/patronictl', '-c', '/etc/patroni.conf', 'dsn'] (Traceback (most recent call last):
File "/opt/patroni/lib/python3.11/site-packages/patroni/ctl.py", line 31, in <module>
from ydiff import markup_to_pager, PatchStream
ImportError: cannot import name 'PatchStream' from 'ydiff' (/opt/patroni/lib/python3.11/site-packages/ydiff.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/patroni/bin/patronictl", line 5, in <module>
from patroni.ctl import ctl
File "/opt/patroni/lib/python3.11/site-packages/patroni/ctl.py", line 33, in <module>
from cdiff import markup_to_pager, PatchStream
ModuleNotFoundError: No module named 'cdiff'
).
```

### What did you expect to happen?

No error, PatchStream properly imported.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 1.2.4
-   PostgreSQL version: 2.9.3
-   DCS (and its version): 

### Patroni configuration file

```yaml
not relevant
```

### patronictl show-config

```yaml
not relevant
```

### Patroni log files

```shell
not relevant
```

### PostgreSQL log files

```shell
not relevant
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by korbajan** [comment]
Yes, Thanks! Sorry, I missed that it was kinda "fixed" https://github.com/patroni/patroni/commit/3fd7c98d2ba394587409aa1d0ff9c447f75402ceI
