### ISSUE TITLE
Unable to deploy haproxy after deploy Patroni on K8s

### ISSUE THREAD

**Issue by PunkFleet** [patroni/patroni#3110]
### What happened?

https://github.com/patroni/patroni/tree/master/kubernetes

I followed this tutorial and successfully deployed patroni to kube. However, there is a bug in the official tutorial: it is not possible to nslookup patronidemo-1 and patronidemo-2. Due to this bug, it is not possible to deploy haproxy next.

### How can we reproduce it (as minimally and precisely as possible)?

Routine deployment. First docker patroni's image, then kubectl apply -f patroni_on_k8s.yaml

### What did you expect to happen?

It should deploy headless patronidemo-0 patronidemo-1 patronidemo-2 properly

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.2
-   PostgreSQL version: 16
-   DCS (and its version): 

### Patroni configuration file

```yaml
I didn't make any changes other than changing the mirror source

# headless service to avoid deletion of patronidemo-config endpoint
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-config
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &cluster_name patronidemo
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  replicas: 3
  serviceName: *cluster_name
  selector:
    matchLabels:
      application: patroni
      cluster-name: *cluster_name
  template:
    metadata:
      labels:
        application: patroni
        cluster-name: *cluster_name
    spec:
      serviceAccountName: patronidemo
      containers:
      - name: *cluster_name
        image: patroni  # docker build -t patroni .
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readiness
            port: 8008
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        env:
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_BYPASS_API_SERVICE
          value: 'true'
        - name: PATRONI_KUBERNETES_USE_ENDPOINTS
          value: 'true'
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni, cluster-name: patronidemo}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: replication-password
        - name: PATRONI_SCOPE
          value: *cluster_name
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/pgroot/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pgdata
        emptyDir: {}
#  volumeClaimTemplates:
#  - metadata:
#      labels:
#        application: spilo
#        spilo-cluster: *cluster_name
#      annotations:
#        volume.alpha.kubernetes.io/storage-class: anything
#      name: pgdata
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      resources:
#        requests:
#          storage: 5Gi

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &cluster_name patronidemo
  labels:
    application: patroni
    cluster-name: *cluster_name
subsets: []

---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patronidemo
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-repl
  labels:
    application: patroni
    cluster-name:  &cluster_name patronidemo
    role: replica
spec:
  type: ClusterIP
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: replica
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: &cluster_name patronidemo
  labels:
    application: patroni
    cluster-name: *cluster_name
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  replication-password: cmVwLXBhc3M=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patronidemo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patronidemo
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  # delete and deletecollection are required only for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
  # delete and deletecollection are required only for for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
# The following privilege is only necessary for creation of headless service
# for patronidemo-config endpoint, in order to prevent cleaning it up by the
# k8s master. You can avoid giving this privilege by explicitly creating the
# service like it is done in this manifest (lines 2..10)
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patronidemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patronidemo
subjects:
- kind: ServiceAccount
  name: patronidemo

# Following privileges are only required if deployed not in the "default"
# namespace and you want Patroni to bypass kubernetes service
# (PATRONI_KUBERNETES_BYPASS_API_SERVICE=true)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patroni-k8s-ep-access
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  resourceNames:
  - kubernetes
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patroni-k8s-ep-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patroni-k8s-ep-access
subjects:
- kind: ServiceAccount
  name: patronidemo
# The namespace must be specified explicitly.
# If deploying to the different namespace you have to change it.
  namespace: default
```
```


### patronictl show-config

```yaml
admin@Kitty pod % kubectl get pods                                                                                     
NAME                   READY   STATUS    RESTARTS   AGE
etcd-0                 1/1     Running   0          2d23h
patronidemo-0          1/1     Running   0          8m18s
patronidemo-1          1/1     Running   0          8m14s
patronidemo-2          1/1     Running   0          8m10s
web-6bd8857656-8s995   1/1     Running   0          6d7h
admin@Kitty pod % kubectl exec -it patronidemo-0 -- /bin/bash
postgres@patronidemo-0:~$ patronictl show-config
postgresql:
  pg_hba:
  - host all all 0.0.0.0/0 md5
  - host replication standby 10.244.1.113/16 md5
  use_pg_rewind: true

```
```


### Patroni log files

```shell
admin@Kitty pod % kubectl logs patronidemo-0
2024-07-25 09:48:07,466 INFO: Selected new K8s API server endpoint https://100.65.40.14:443
2024-07-25 09:48:07,493 INFO: No PostgreSQL configuration items changed, nothing to reload.
2024-07-25 09:48:07,497 INFO: Lock owner: ; I am patronidemo-0
2024-07-25 09:48:07,632 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory /home/postgres/pgdata/pgroot/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start

2024-07-25 09:48:08.909 UTC [31] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-07-25 09:48:08.909 UTC [31] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-25 09:48:08.914 UTC [31] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-25 09:48:08.920 UTC [34] LOG:  database system was shut down at 2024-07-25 09:48:08 UTC
2024-07-25 09:48:08,920 INFO: postmaster pid=31
2024-07-25 09:48:08.928 UTC [31] LOG:  database system is ready to accept connections
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2024-07-25 09:48:09,022 INFO: establishing a new patroni heartbeat connection to postgres
2024-07-25 09:48:09,091 INFO: running post_bootstrap
2024-07-25 09:48:09,099 WARNING: Could not activate Linux watchdog device: Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'
2024-07-25 09:48:09,102 INFO: Reaped pid=44, exit status=0
2024-07-25 09:48:09,105 INFO: Reaped pid=45, exit status=0
2024-07-25 09:48:09,307 INFO: initialized a new cluster
2024-07-25 09:48:12.010 UTC [32] LOG:  checkpoint starting: force wait
2024-07-25 09:48:12.468 UTC [32] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.405 s, sync=0.002 s, total=0.459 s; sync files=6, longest=0.002 s, average=0.001 s; distance=9037 kB, estimate=9037 kB; lsn=0/2000060, redo lsn=0/2000028
2024-07-25 09:48:13.106 UTC [49] ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:13.106 UTC [49] STATEMENT:  START_REPLICATION SLOT "patronidemo_1" 0/3000000 TIMELINE 1
2024-07-25 09:48:13.118 UTC [50] ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:13.118 UTC [50] STATEMENT:  START_REPLICATION SLOT "patronidemo_1" 0/3000000 TIMELINE 1
2024-07-25 09:48:15.534 UTC [32] LOG:  checkpoint starting: force wait
2024-07-25 09:48:15.592 UTC [32] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.059 s; sync files=0, longest=0.000 s, average=0.000 s; distance=16384 kB, estimate=16384 kB; lsn=0/3000060, redo lsn=0/3000028
2024-07-25 09:48:16.264 UTC [53] ERROR:  replication slot "patronidemo_2" does not exist
2024-07-25 09:48:16.264 UTC [53] STATEMENT:  START_REPLICATION SLOT "patronidemo_2" 0/4000000 TIMELINE 1
2024-07-25 09:48:16.279 UTC [54] ERROR:  replication slot "patronidemo_2" does not exist
2024-07-25 09:48:16.279 UTC [54] STATEMENT:  START_REPLICATION SLOT "patronidemo_2" 0/4000000 TIMELINE 1
2024-07-25 09:48:18.121 UTC [56] ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:18.121 UTC [56] STATEMENT:  START_REPLICATION SLOT "patronidemo_1" 0/3000000 TIMELINE 1
2024-07-25 09:48:19,231 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:48:29,217 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:48:39,156 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:48:49,156 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:48:59,156 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:49:09,157 INFO: no action. I am (patronidemo-0), the leader with the lock
....
2024-07-25 09:53:09,158 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:53:15.692 UTC [32] LOG:  checkpoint starting: time
2024-07-25 09:53:19,156 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:53:19.820 UTC [32] LOG:  checkpoint complete: wrote 42 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.113 s, sync=0.003 s, total=4.128 s; sync files=10, longest=0.002 s, average=0.001 s; distance=16693 kB, estimate=16693 kB; lsn=0/404D5F0, redo lsn=0/404D5B8
2024-07-25 09:53:29,213 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:53:39,156 INFO: no action. I am (patronidemo-0), the leader with the lock
2024-07-25 09:53:49,156 INFO: no action. I am (patronidemo-0), the leader with the lock
.....
2024-07-25 09:57:19,159 INFO: no action. I am (patronidemo-0), the leader with the lock
admin@Kitty pod % kubectl logs patronidemo-1
2024-07-25 09:48:11,824 INFO: Selected new K8s API server endpoint https://100.65.40.14:443
2024-07-25 09:48:11,846 INFO: No PostgreSQL configuration items changed, nothing to reload.
2024-07-25 09:48:11,849 INFO: Lock owner: patronidemo-0; I am patronidemo-1
2024-07-25 09:48:11,921 INFO: trying to bootstrap from leader 'patronidemo-0'
2024-07-25 09:48:12,714 INFO: replica has been created using basebackup
2024-07-25 09:48:12,714 INFO: bootstrapped from leader 'patronidemo-0'
2024-07-25 09:48:13.041 UTC [21] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-07-25 09:48:13.042 UTC [21] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-25 09:48:13.046 UTC [21] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-25 09:48:13.052 UTC [24] LOG:  database system was interrupted; last known up at 2024-07-25 09:48:12 UTC
2024-07-25 09:48:13,051 INFO: postmaster pid=21
2024-07-25 09:48:13.086 UTC [24] LOG:  entering standby mode
2024-07-25 09:48:13.087 UTC [24] LOG:  starting backup recovery with redo LSN 0/2000028, checkpoint LSN 0/2000060, on timeline ID 1
2024-07-25 09:48:13.089 UTC [24] LOG:  redo starts at 0/2000028
2024-07-25 09:48:13.090 UTC [24] LOG:  completed backup recovery with redo LSN 0/2000028 and end LSN 0/2000100
2024-07-25 09:48:13.090 UTC [24] LOG:  consistent recovery state reached at 0/2000100
2024-07-25 09:48:13.090 UTC [21] LOG:  database system is ready to accept read-only connections
localhost:5432 - accepting connections
2024-07-25 09:48:13.102 UTC [26] FATAL:  could not start WAL streaming: ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:13.116 UTC [29] FATAL:  could not start WAL streaming: ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:13.116 UTC [24] LOG:  waiting for WAL to become available at 0/3000018
localhost:5432 - accepting connections
2024-07-25 09:48:13,144 INFO: Reaped pid=31, exit status=0
2024-07-25 09:48:13,145 INFO: Lock owner: patronidemo-0; I am patronidemo-1
2024-07-25 09:48:13,145 INFO: establishing a new patroni heartbeat connection to postgres
2024-07-25 09:48:13.160 UTC [34] FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption
2024-07-25 09:48:13,161 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1072, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1067, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/connection.py", line 157, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/psycopg.py", line 104, in connect
    ret = _connect(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption

2024-07-25 09:48:13,219 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:18.118 UTC [36] FATAL:  could not start WAL streaming: ERROR:  replication slot "patronidemo_1" does not exist
2024-07-25 09:48:18.118 UTC [24] LOG:  waiting for WAL to become available at 0/3000018
2024-07-25 09:48:19.156 UTC [37] FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption
2024-07-25 09:48:19,152 INFO: Lock owner: patronidemo-0; I am patronidemo-1
2024-07-25 09:48:19,156 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1072, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1067, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/connection.py", line 157, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/psycopg.py", line 104, in connect
    ret = _connect(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption

2024-07-25 09:48:19,158 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:23.119 UTC [39] LOG:  started streaming WAL from primary at 0/3000000 on timeline 1
2024-07-25 09:48:29,223 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:39,160 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
....
2024-07-25 09:52:59,160 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:09,161 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:13.096 UTC [22] LOG:  restartpoint starting: time
2024-07-25 09:53:17.225 UTC [22] LOG:  restartpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.118 s, sync=0.003 s, total=4.130 s; sync files=10, longest=0.002 s, average=0.001 s; distance=16384 kB, estimate=16384 kB; lsn=0/3000060, redo lsn=0/3000028
2024-07-25 09:53:17.226 UTC [22] LOG:  recovery restart point at 0/3000028
2024-07-25 09:53:17.226 UTC [22] DETAIL:  Last completed transaction was at log time 2024-07-25 09:49:39.079784+00.
2024-07-25 09:53:19,158 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
......
2024-07-25 09:57:09,161 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:57:19,164 INFO: no action. I am (patronidemo-1), a secondary, and following a leader (patronidemo-0)
admin@Kitty pod % kubectl logs patronidemo-2
2024-07-25 09:48:15,376 INFO: Selected new K8s API server endpoint https://100.65.40.14:443
2024-07-25 09:48:15,400 INFO: No PostgreSQL configuration items changed, nothing to reload.
2024-07-25 09:48:15,403 INFO: Lock owner: patronidemo-0; I am patronidemo-2
2024-07-25 09:48:15,478 INFO: trying to bootstrap from leader 'patronidemo-0'
2024-07-25 09:48:15,810 INFO: replica has been created using basebackup
2024-07-25 09:48:15,811 INFO: bootstrapped from leader 'patronidemo-0'
2024-07-25 09:48:16.187 UTC [20] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-07-25 09:48:16.187 UTC [20] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-25 09:48:16.191 UTC [20] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-25 09:48:16,197 INFO: postmaster pid=20
2024-07-25 09:48:16.201 UTC [24] LOG:  database system was interrupted; last known up at 2024-07-25 09:48:15 UTC
2024-07-25 09:48:16.236 UTC [25] FATAL:  the database system is starting up
localhost:5432 - rejecting connections
2024-07-25 09:48:16.242 UTC [24] LOG:  entering standby mode
2024-07-25 09:48:16.243 UTC [24] LOG:  starting backup recovery with redo LSN 0/3000028, checkpoint LSN 0/3000060, on timeline ID 1
2024-07-25 09:48:16.246 UTC [24] LOG:  redo starts at 0/3000028
2024-07-25 09:48:16.247 UTC [24] LOG:  completed backup recovery with redo LSN 0/3000028 and end LSN 0/3000100
2024-07-25 09:48:16.247 UTC [24] LOG:  consistent recovery state reached at 0/3000100
2024-07-25 09:48:16.247 UTC [20] LOG:  database system is ready to accept read-only connections
2024-07-25 09:48:16.262 UTC [27] FATAL:  could not start WAL streaming: ERROR:  replication slot "patronidemo_2" does not exist
localhost:5432 - accepting connections
2024-07-25 09:48:16.277 UTC [28] FATAL:  could not start WAL streaming: ERROR:  replication slot "patronidemo_2" does not exist
2024-07-25 09:48:16.278 UTC [24] LOG:  waiting for WAL to become available at 0/4000018
2024-07-25 09:48:16,278 INFO: Lock owner: patronidemo-0; I am patronidemo-2
2024-07-25 09:48:16,278 INFO: establishing a new patroni heartbeat connection to postgres
2024-07-25 09:48:16.295 UTC [33] FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption
2024-07-25 09:48:16,296 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1072, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1067, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/connection.py", line 157, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/psycopg.py", line 104, in connect
    ret = _connect(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption

2024-07-25 09:48:16,359 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:19.157 UTC [35] FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption
2024-07-25 09:48:19,153 INFO: Lock owner: patronidemo-0; I am patronidemo-2
2024-07-25 09:48:19,157 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1072, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/__init__.py", line 1067, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/postgresql/connection.py", line 157, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/patroni/psycopg.py", line 104, in connect
    ret = _connect(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", no encryption

2024-07-25 09:48:19,158 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:21.274 UTC [36] LOG:  started streaming WAL from primary at 0/4000000 on timeline 1
2024-07-25 09:48:29,220 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:48:39,161 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
.......
2024-07-25 09:53:19,160 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:29,220 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:31.308 UTC [22] LOG:  restartpoint starting: time
2024-07-25 09:53:35.432 UTC [22] LOG:  restartpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.114 s, sync=0.003 s, total=4.125 s; sync files=10, longest=0.002 s, average=0.001 s; distance=16693 kB, estimate=16693 kB; lsn=0/404D5F0, redo lsn=0/404D5B8
2024-07-25 09:53:35.432 UTC [22] LOG:  recovery restart point at 0/404D5B8
2024-07-25 09:53:35.432 UTC [22] DETAIL:  Last completed transaction was at log time 2024-07-25 09:49:39.079784+00.
2024-07-25 09:53:39,160 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:49,164 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:53:59,164 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
.......
2024-07-25 09:57:19,163 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
2024-07-25 09:57:29,159 INFO: no action. I am (patronidemo-2), a secondary, and following a leader (patronidemo-0)
```
```


### PostgreSQL log files

```shell
admin@Kitty pod % kubectl exec -it patronidemo-0 -- /bin/bash
postgres@patronidemo-0:~$ cd /home/postgres/pgdata/pg_log
bash: cd: /home/postgres/pgdata/pg_log: No such file or directory
postgres@patronidemo-0:~$ cd /var/log/postgresql
postgres@patronidemo-0:/var/log/postgresql$ cat postgresql.log
cat: postgresql.log: No such file or directory
postgres@patronidemo-0:/var/log/postgresql$ ls
postgres@patronidemo-0:/var/log/postgresql$ 
```
```


### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

_No response_

**Comment by CyberDem0n** [comment]
> there is a bug in the official tutorial:
It should deploy headless patronidemo-0 patronidemo-1 patronidemo-2 properly

Well, the readme clearly says - "Kubernetes deployment **examples**", you may extend or change them based on your needs.

Also, this deployment was never designed for HAProxy.
In fact, the HAProxy is even not required. There are already two services:
- service/patronidemo - to connect to the primary
- service/patronidemo-repl - to connect to replica pods.
