### ISSUE TITLE
Patroni timeout connect to etcd and stuck when trying save key to etcd

### ISSUE THREAD

**Issue by cuong-max** [patroni/patroni#3199]
### What happened?

When etcd switch the leader's node, causing patroni to temporarily lose connection to etcd. After patroni connected to etcd, I saw 2 replica node cannot sync data with leader node

### How can we reproduce it (as minimally and precisely as possible)?

When etcd increase time to R/W k/v to disk or slow disk 

### What did you expect to happen?

I expected patroni can retry to connect to etcd and sync data

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 13.12.0
-   DCS (and its version): etcd version 3.5.2

### Patroni configuration file

```yaml
scope: database-cluster
name: database-IP
restapi:
    listen: IP:PORT
    connect_address: IP:PORT

etcd:
    hosts: IP:PORT,
    hosts: IP2:PORT,
    hosts: IP3:PORT
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

postgresql:
    listen: IP:PORT
    connect_address: IP:PORT
    data_dir: path
    pgpass: path
    authentication: ***
    parameters:
        unix_socket_directories: path
        archive_mode: off
        logging_collector: true
        log_directory: path
        log_rotation_size: 50000
        log_filename: postgres.log
        log_truncate_on_rotation: true
        max_connections: 400
        shared_buffers: 4GB
        log_min_duration_statement: 1000

log:
    level: INFO
    dir: path
    file_num: 1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 400
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2024-10-30 04:30:37,903 INFO: no action. I am (database-IP), the leader with the lock
2024-10-30 04:30:47,894 INFO: no action. I am (database-IP), the leader with the lock
2024-10-30 04:30:57,786 INFO: no action. I am (database-IP), the leader with the lock
2024-10-30 04:31:07,771 INFO: Lock owner: database-IP; I am database-IP
2024-10-30 04:31:11,123 INFO: Selected new etcd server http://IP:PORT
2024-10-30 04:31:11,123 ERROR: Request to server http://IP:PORT failed: MaxRetryError('HTTPConnectionPool(host=\'IP\', port=PORT): Max retries exceeded with url: /v2/keys/service/database-cluster/status (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'IP\', port=PORT): Read timed out. (read timeout=3.333237828065952)"))')
2024-10-30 04:31:11,123 INFO: Reconnection allowed, looking for another server.
2024-10-30 04:31:11,123 ERROR: 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host=IP, port=PORT): Read timed out. (read timeout=3.333237828065952)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/patroni/dcs/etcd.py", line 233, in _do_http_request
    response = request_executor(method, base_uri + path, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=IP, port=PORT): Max retries exceeded with url: /v2/keys/service/database-cluster/status (Caused by ReadTimeoutError("HTTPConnectionPool(host=IP, port=PORT): Read timed out. (read timeout=3.333237828065952)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/patroni/dcs/etcd.py", line 511, in handle_etcd_exceptions
    retval = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/patroni/dcs/etcd.py", line 790, in _write_status
    return bool(self._client.set(self.status_path, value))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/etcd/client.py", line 721, in set
    return self.write(key, value, ttl=ttl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/patroni/dcs/etcd.py", line 282, in api_execute
    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/patroni/dcs/etcd.py", line 254, in _do_http_request
    raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
etcd.EtcdException: PUT /v2/keys/service/database-cluster/status request failed
2024-10-30 04:31:12,850 INFO: no action. I am (database-IP), the leader with the lock
2024-10-30 04:31:17,809 INFO: no action. I am (database-IP), the leader with the lock
2024-10-30 04:31:27,794 INFO: acquired session lock as a leader
2024-10-30 04:31:37,917 INFO: acquired session lock as a leader
2024-10-30 04:31:47,789 INFO: acquired session lock as a leader
2024-10-30 04:31:57,794 INFO: acquired session lock as a leader
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> Patroni version: 3.1.0

The issue template clearly says  "Before reporting a bug please make sure to **reproduce it with the latest Patroni version**!"

And, the latest version is 4.0.3.
