### ISSUE TITLE
Latest ydiff version incompatibility

### ISSUE THREAD

**Issue by vaol** [patroni/patroni#3212]
### What happened?

We just installed Patroni 4.0.3 and edit-config does not work because a compatibility issue with the latest version of ydiff.

Downgrading `ydiff` to 1.2.0 solves the issue.

```bash
[postgres@production-db-3 ~]$ patronictl -k edit-config
Traceback (most recent call last):
  File "/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
             ^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/applic/patroni_venv/lib64/python3.11/site-packages/patroni/ctl.py", line 2122, in edit_config
    show_diff(before_editing, after_editing)
  File "/applic/patroni_venv/lib64/python3.11/site-packages/patroni/ctl.py", line 1917, in show_diff
    markup_to_pager(PatchStream(buf), opts)
  File "/applic/patroni_venv/lib64/python3.11/site-packages/ydiff.py", line 640, in markup_to_pager
    theme=opts.theme)
          ^^^^^^^^^^
AttributeError: type object 'opts' has no attribute 'theme'
```

Library installed during the installation:
Package         Version
--------------- -----------
click           8.1.7
dnspython       2.7.0
patroni         4.0.3
pip             24.3.1
prettytable     3.12.0
psutil          6.1.0
psycopg2-binary 2.9.10
python-dateutil 2.9.0.post0
python-etcd     0.4.5
PyYAML          6.0.2
setuptools      75.5.0
six             1.16.0
urllib3         2.2.3
wcwidth         0.2.13
ydiff           1.4.1

### How can we reproduce it (as minimally and precisely as possible)?

Install latest patroni version and run
```bash
patronictl edit-config
```

### What did you expect to happen?

edit-config to work

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.3
-   PostgreSQL version: 13.13
-   DCS (and its version): ETCD 3.5.9

### Patroni configuration file

```yaml
scope: patroni
namespace: /service/
name: production-db-3

log:
  level: INFO
  dir: /var/log/patroni
  file_size: 50000000 # Size of log file which triggers a log rotation
  file_num: 10 # Number of logs to retain
  dateformat: '%Y-%m-%d %H:%M:%S'

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      keep_existing_recovery_conf: true
      recovery_conf:
        restore_command: /usr/bin/pgbackrest --stanza=production archive-get %f %p
        recovery_target_timeline: latest
  method: initdb
  initdb:
    - data-checksums
    - encoding: UTF8
    - locale: en_US.utf8
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication rep_user 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: dsfdsfsdfdsfdsfsdfsdf.internal:5432
  data_dir: /data/postgres/13/pg_data

  bin_dir: /usr/pgsql-13/bin

  use_unix_socket: false
  pgpass: /home/postgres/.pgpass
  pg_ctl_timeout: 60
  use_pg_rewind: true
  remove_data_directory_on_rewind_failure: false
  authentication:
    superuser:
      username: postgres
    replication:
      username: repuser
    rewind:
      username: repuser
  create_replica_methods:
    - pgbackrest
  pgbackrest:
    command: /usr/bin/pgbackrest --log-level-file=detail --link-all --delta --stanza=production restore
    no_params: true
    keep_data: true

restapi:
  listen: 0.0.0.0:8008
  connect_address: production-db-3.internal:8008
  certfile: /etc/ssl/certs/production-db-3.c.internal.crt
  keyfile: /etc/ssl/certs/production-db-3.c.internal.key
  cafile: /etc/ssl/certs/production-db-3.internal.crt

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

etcd:
  host: 127.0.0.1:2379
  hosts:
    - 1.2.3.4:2379
    - 1.2.3.5:2379
    - 1.2.3.6:2379
  protocol: http

tags:
    nosync: true
    nofailover: true
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 10
maximum_lag_on_failover: 1048576
postgresql:
  keep_existing_recovery_conf: true
  parameters:
    max_locks_per_transaction: 512
  recovery_conf:
    recovery_target_timeline: latest
    restore_command: /usr/bin/pgbackrest --stanza=production archive-get %f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by islamyakin** [comment]
when  will the latest version be released ?
