### ISSUE TITLE
Please disallow Patroni from running several pg_basebackups at the same time

### ISSUE THREAD

**Issue by HansSchreder** [patroni/patroni#3220]
### What happened?

Multiple invocations of 'patronictl reinit' spawned two pg_basebackup processes.
Both processes tried to backup the same leader database, first one worked for about 30 minutes, second one - for about 9 minutes.
Second pg_basebackup completed successfully, the replica was reinitialized, while first pg_basebackup continued.
First pg_basebackup lost connection to the leader database, and removed replicas' $PGDATA.

### How can we reproduce it (as minimally and precisely as possible)?

Make somewhat large Postgres Database Cluster.
Configure Patroni.
Create a replica.

Run 'partonictl reinit', send SIGTERM to pg_basebackup process to cause patroni to restart it.
Run another 'partonictl reinit' while first one is still running.

Observe two pg_basebackup processes.

### What did you expect to happen?

Patroni should not have spawn a single pg_basebackup, denying second 'patronictl reinit'.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.5
-   PostgreSQL version: 15.6
-   DCS (and its version): etcd 3.4.23

### Patroni configuration file

```yaml
scope: xxx-patroni
name: xxx-yyy

restapi:
    listen: xxx.xxx.xxx.xxx:8008
    connect_address: xxx.xxx.xxx.xxx:8008
    authentication:
      username: patroni
      password: xxx

etcd3:
    hosts:
    - xxx.xxx.xxx.xxx:2379
    - xxx.xxx.xxx.xxx:2379
    - xxx.xxx.xxx.xxx:2379
    username: etcd
    password: xxx

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        synchronous_mode: true
        postgresql:
            use_pg_rewind: true
            parameters:
                shared_buffers: 4000MB
                effective_cache_size: 12000MB
                autovacuum_vacuum_cost_limit: 133
                autovacuum_max_workers: 2
                autovacuum_analyze_scale_factor: 0.01
                autovacuum_vacuum_scale_factor: 0.05
                default_transaction_isolation: read committed
                maintenance_work_mem: 2048MB
                max_wal_size: 16384MB
                wal_keep_segments: 512
                work_mem: 18MB
                temp_file_limit: 6164MB
                effective_io_concurrency: 200
                log_file_mode: 420
                track_io_timing: True
                track_activity_query_size: 4096
                max_connections: 512
                random_page_cost: 1.1
                log_connections: on
                log_disconnections: on
                log_hostname: on
                min_wal_size: 1096MB
                shared_preload_libraries: pg_stat_statements,pgaudit
                pgaudit.log: DDL,role
                pgaudit.log_catalog: True
                log_file_mode: 0644
                archive_command: test ! -f /pg_walarchive/%f && cp %p /pg_walarchive/%f
                restore_command: cp /pg_walarchive/%f %p
                archive_mode: True
                log_filename: postgresql-%a.log
                logging_collector: True
                log_truncate_on_rotation: True
                log_rotation_size: 0

    initdb:
    - encoding: UTF-8
    - data-checksums

postgresql:
    listen: xxx.xxx.xxx.xxx
    connect_address: xxx.xxx.xxx.xxx
    data_dir: /pg_data/data
    bin_dir: /usr/lib/postgresql/15/bin
    pgpass: /var/lib/pgsql/.pgpass_patroni
    pg_hba:
    - local all postgres peer
    - host replication repluser 0.0.0.0/0 md5
    - host all +postgres 127.0.0.1/32 md5
    - host all +postgres 10.183.213.119/32 md5
    - host all +postgres 10.158.107.102/32 md5
    - host all +postgres all reject
    - host all all all md5
    authentication:
        replication:
            username: repluser
            password: xxx
        superuser:
            username: postgres
            password: xxx
        rewind:
            username: rewinduser
            password: xxx

    parameters:
        unix_socket_directories: '/run/postgresql'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  file_size: 10485760
  file_num: 10
  dir: /pg_audit/log/patroni
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: test ! -f /pg_walarchive/%f && cp %p /pg_walarchive/%f
    archive_mode: true
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_max_workers: 2
    autovacuum_vacuum_cost_limit: 133
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_timeout: 1800
    default_transaction_isolation: read committed
    effective_cache_size: 12000MB
    effective_io_concurrency: 200
    log_connections: true
    log_disconnections: true
    log_file_mode: 420
    log_filename: postgresql-%a.log
    log_hostname: true
    log_rotation_size: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 2048MB
    max_connections: 538
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 2
    max_wal_size: 16384MB
    max_worker_processes: 8
    min_wal_size: 4096MB
    pgaudit.log: DDL,role
    pgaudit.log_catalog: true
    random_page_cost: 1.1
    restore_command: cp /pg_walarchive/%f %p
    shared_buffers: 4000MB
    shared_preload_libraries: pg_stat_statements,pgaudit
    temp_file_limit: 6164MB
    track_activity_query_size: 4096
    track_io_timing: true
    wal_keep_segments: 512
    work_mem: 18MB
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
first 'partonictl reinit' restarts:
12:44:33,756 WARNING: Cancelling long running task bootstrap from leader '<leader>'
12:44:33,757 INFO: Terminating ['/usr/lib/postgresql/15/bin/pg_basebackup', '--pgdata=/pg_data/data', '-X', 'stream', '--dbname=dbname=postgres user=repluser host=xxx.xxx.xxx.xxx port=5432']
12:44:33,758 ERROR: Error when fetching backup: pg_basebackup exited with code=-15
12:44:33,758 ERROR: failed to bootstrap from leader 'p0grnt-pgc005lk'
12:44:33,758 INFO: Removing data directory: /pg_data/data
12:44:34,178 INFO: Lock owner: <leader>; I am <replica>
12:44:34,277 INFO: trying to bootstrap from leader '<leader>'
12:44:43,776 WARNING: Killed ['/usr/lib/postgresql/15/bin/pg_basebackup', '--pgdata=/pg_data/data', '-X', 'stream', '--dbname=dbname=postgres user=repluser host=xxx.xxx.xxx.xxx port=5432'] because it was still running
12:44:43,777 ERROR: Error when fetching backup: pg_basebackup exited with code=-9
12:44:43,777 WARNING: Trying again in 5 seconds

first 'patronictl reinit' restarts:
12:44:44,177 INFO: Lock owner: <leader>; I am <replica>
12:44:44,227 INFO: bootstrap from leader '<leader>' in progress

second 'partonictl reinit' starts:
12:46:37,018 INFO: Selected new etcd server http://xxx.xxx.xxx.xxx:2379
12:46:37,019 INFO: Trying to authenticate on Etcd...
12:46:37,122 INFO: No PostgreSQL configuration items changed, nothing to reload.
12:46:37,217 INFO: trying to bootstrap from leader '<leader>'

second 'partonictl reinit' finishes:
12:55:40,393 INFO: replica has been created using basebackup
12:55:40,394 INFO: bootstrapped from leader '<leader>'
12:55:40,816 INFO: postmaster pid=12762

first 'partonictl reinit' fails:
13:17:54,298 WARNING: max_connections setting is missing from pg_controldata output
13:17:54,298 WARNING: max_prepared_xacts setting is missing from pg_controldata output
13:17:54,298 WARNING: max_locks_per_xact setting is missing from pg_controldata output
13:17:54,298 WARNING: max_worker_processes setting is missing from pg_controldata output
13:17:54,298 WARNING: max_wal_senders setting is missing from pg_controldata output
13:17:54,307 ERROR: Exception during execution of long running task restarting after failure
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 903, in follow
    ret = self.start(timeout=timeout, block_callbacks=change_role, role=role) or None
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 549, in start
    self.config.write_postgresql_conf(configuration)
  File "/usr/lib/python3/dist-packages/patroni/postgresql/config.py", line 390, in write_postgresql_conf
    os.rename(self._postgresql_conf, self._postgresql_base_conf)
FileNotFoundError: [Errno 2] No such file or directory: '/pg_data/data/postgresql.conf' -> '/pg_data/data/postgresql.base.conf'
```

### PostgreSQL log files

```shell
first 'patronictl reinit' restarts (leader log):
12:44:48 [22320]: db=[unknown],user=repluser,app=[unknown],client=<replica> LOG:  replication connection authorized: user=repluser application_name=pg_basebackup

second 'partonictl reinit' starts (leader log):
12:46:37 [23578]: db=[unknown],user=repluser,app=[unknown],client=<replica> LOG:  replication connection authorized: user=repluser application_name=pg_basebackup

second 'patronictl reinit' finishes (leader log):
12:55:38 [23578]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> LOG:  disconnection: session time: 0:09:00.803 user=repluser database= host=<replica> port=51468

first 'patronictl reinit' fails (leader log):
13:17:46 [22320]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> LOG:  could not send data to client: Connection reset by peer
13:17:46 [22320]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> STATEMENT:  BASE_BACKUP ( LABEL 'pg_basebackup base backup',  PROGRESS,  WAIT 0,  MANIFEST 'yes',  TARGET 'client')
13:17:46 [22320]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> FATAL:  connection to client lost
13:17:46 [22320]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> STATEMENT:  BASE_BACKUP ( LABEL 'pg_basebackup base backup',  PROGRESS,  WAIT 0,  MANIFEST 'yes',  TARGET 'client')
13:17:46 [22320]: db=[unknown],user=repluser,app=pg_basebackup,client=<replica> LOG:  disconnection: session time: 0:32:57.918 user=repluser database= host=<replica> port=33988


replica log:
13:17:47 [13866]: db=,user=,app=,client=LOG:  could not create archive status file "pg_wal/archive_status/00000003000000700000005A.done": No such file or directory
13:17:48 [12777]: db=,user=,app=,client=PANIC:  could not open file "/pg_data/data/global/pg_control": No such file or directory
13:17:48 [12777]: db=,user=,app=,client=CONTEXT:  writing block 92283 of relation base/35976/57543
13:17:48 [13866]: db=,user=,app=,client=LOG:  could not create archive status file "pg_wal/archive_status/00000003000000700000005B.done": No such file or directory
13:17:50 [12762]: db=,user=,app=,client=LOG:  background writer process (PID 12777) was terminated by signal 6: Aborted
13:17:50 [12762]: db=,user=,app=,client=LOG:  terminating any other active server processes
13:17:53 [29141]: db=[unknown],user=[unknown],app=[unknown],client=localhostLOG:  connection received: host=localhost port=58252
13:17:53 [29141]: db=postgres,user=postgres,app=[unknown],client=localhostFATAL:  the database system is in recovery mode
13:17:53 [12762]: db=,user=,app=,client=LOG:  all server processes terminated; reinitializing
13:17:53 [12762]: db=,user=,app=,client=LOG:  could not open directory "base": No such file or directory
13:17:53 [12762]: db=,user=,app=,client=LOG:  could not open directory "pg_tblspc": No such file or directory
13:17:53 [12762]: db=,user=,app=,client=PANIC:  could not open file "global/pg_control": No such file or directory
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> Patroni version: 2.1.5

the latest version is 4.0.3
